import 'package:mealmetrics/app/data/shared/constants_methods.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserModel {
  UserModel({this.genero, this.gda, this.peso, this.altura, this.idade, this.fa});
  UserModel.fromJson(Map<String, dynamic> json) {
    genero = json['genero']?.toString();
    gda = double.tryParse(ConstantMethods.removeDecimalIfZero(json['gda'].toString()));
    peso = json['peso']?.toDouble();
    altura = json['altura']?.toString();
    idade = json['idade']?.toString();
    fa = json['fa']?.toString();
  }
  /*
{
  "genero": "",              // "masculino" ou "feminino"
  "GDA": 1,                 //   Gasto calorico diário estimado
  "peso": 2.3,             // em kg
  "altura": "180",      // em cm
  "idade": "25",       // em anos  
  "FA": "hello"
} 
*/

  String? genero;
  double? gda;
  double? peso;
  String? altura;
  String? idade;
  String? fa;
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['genero'] = genero;
    data['gda'] = gda;
    data['peso'] = peso;
    data['altura'] = altura;
    data['idade'] = idade;
    data['fa'] = fa;
    return data;
  }
}
