///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AlimentoModel {
  AlimentoModel({
    required this.descricao,
    this.proteinas,
    this.carboidratos,
    this.gorduras,
    this.calorias,
  }) {
    calorias = calcularCalorias();
  }

  AlimentoModel.fromJson(Map<String, dynamic> json) {
    descricao = json['descricao']?.toString();
    proteinas = json['proteinas']?.toDouble();
    carboidratos = json['carboidratos']?.toDouble();
    gorduras = json['gorduras']?.toDouble();
    calorias = json['calorias']?.toDouble() ?? calcularCalorias();
  }
  String? descricao;
  double? proteinas;
  double? carboidratos;
  double? gorduras;
  double? calorias;

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['descricao'] = descricao;
    data['proteinas'] = proteinas;
    data['carboidratos'] = carboidratos;
    data['gorduras'] = gorduras;
    data['calorias'] = calorias;
    return data;
  }

  double calcularCalorias() {
    return (proteinas ?? 0) * 4 + (carboidratos ?? 0) * 4 + (gorduras ?? 0) * 9;
  }
}
