///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UnidadeModel {
  UnidadeModel({required this.nome, required this.sigla});
  UnidadeModel.fromJson(Map<String, dynamic> json) {
    nome = json['nome']?.toString();
    sigla = json['sigla']?.toString();
  }
  /*
{
  "nome": "quilo",
  "sigla": "kg"
} 
*/

  String? nome;
  String? sigla;
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['nome'] = nome;
    data['sigla'] = sigla;
    return data;
  }
}
